### ISSUE TITLE
RadioButton与Checkbox的动画在Chromium引擎下缺少一部分

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#278]
自从某个版本的Chromium开始，RadioButton与Checkbox的动画就一直缺少一部分，Safari和Firefox经过测试均正常。

**Comment by otomad** [comment]
与跟踪链接中的问题无关，跟踪链接中：

```css
@keyframes fade {
    from {
        --color: var(--light);
    }
    to {
        --color: var(--dark);
    }
}
```

意外将 CSS 自定义属性 `--color` 置入了关键帧动画中，这是不允许的，因为 CSS 不知道 `--color` 是什么类型的。除非使用 `@property --color` 特性，将自定义属性注册为全局属性并向其分配类型、继承等附加信息，这样才会正常工作。不推荐过多地使用 `@property` 特性，因为全局变量不易维护，并且容易与其它属性重名造成意外的结果。

本案使用 box-shadow 作为动画属性，不受影响。

至于显示颜色变量无法正确获取，这是 Chromium DevTools 审查元素工具的 bug，虽显示如此，但实际上是可以正常获取的。不信你可以对一个无关元素应用最小预置的关键帧动画，例如以颜色变量只改变 color 属性。

请重新审视产生问题的原因。
